[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "measyjson"
version = "0.1.0"
description = "A simple library to make working with JSON data easier."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "kirobotdev" }]
keywords = ["json", "utilities", "parser", "serialization"]
requires-python = ">=3.9"
dependencies = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/myndevdev/easyjson"
Repository = "https://github.com/myndevdev/easyjson"
Issues = "https://github.com/myndevdev/easyjson/issues"

[dependency-groups]
dev = ["pytest>=8.0"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
easyjson = ["py.typed"]

[tool.pytest.ini_options]
testpaths = ["tests"]
